---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.15-alpine3.13
  commands:
  - go version
  - go fmt ./...
  # - go vet ./...

- name: docker-build
  image: plugins/docker
  settings:
    repo: guessi/mailgun-tracker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

...
