mailgun:
  domain: example.com
  apiKey: key-01234567890123456789
  ignoreEventTypes:
  - unknown
  - generic
  - bounce
  - espblock
  - greylisted
  - blacklisted
  - suppress-bounce
  - suppress-complaint
  - suppress-unsubscribe
  - old
  - hardfail
  bounceAlerts:
  - bounce-test1@example.com
  - bounce-test2@example.com
  - bounce-test3@example.com
  ignoreSubjectKeywords:
  - keyword1
  - keyword2
  ignoreRecipientKeywords:
  - keyword1
  - keyword2

cron:
  checkPeriod: "@every 60s"

slack:
  username: "Mailgun Tracker"
  channelGeneral: "#general"
  channelEmergency: "#general"
  webhook: "https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  iconUrl: "https://pbs.twimg.com/profile_images/1989918123/ICON_MAILGUN_NOFX_reasonably_small.png"
  footerText: "mailgun-tracker"
